# This is only required with osxcross to cross-compile
# from linux to macOS, and is not covered (yet) by gradle-rust.

# also this isn't used anywhere iirc i was just testing stuff

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
ar = "x86_64-apple-darwin14-ar"